# overrides for local development
version: '3'
db:
  image: postgres:9.6
  environment:
    POSTGRES_PASSWORD: 123456
    POSTGRES_USER: mrqa
  volumes:
    - pgdata:/var/lib/postgresql/data
  expose:
    - 5432
services:
  api:
    # this starts up nodemon so it dynamically takes in changes
    entrypoint: ["npm", "run", "dev"]
    volumes:
      # This will mount in your source code into the image
      - .:/app
